import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Its default export is the item array itself, ready to splice into a
// category. Regenerate with `npm run gen-api-docs`; never hand-edit.
import restApiSidebar from './docs/api-reference/rest/sidebar';

/**
 * The six top-level categories are the shared shape every warehouse-systems
 * documentation site uses, in this order: Overview, Business Context,
 * Domain-Driven Design, API Reference, Ecosystem, Architecture Decision
 * Records.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/index'},
      items: ['overview/getting-started'],
    },
    {
      type: 'category',
      label: 'Business Context',
      collapsed: false,
      items: [
        'business-context/domain-vision',
        'business-context/ubiquitous-language',
        'business-context/location-code',
      ],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      collapsed: false,
      items: [
        'ddd/subdomain-classification',
        'ddd/aggregates',
        'ddd/invariants',
        'ddd/domain-events',
        'ddd/hexagonal-architecture',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      link: {type: 'doc', id: 'api-reference/index'},
      items: [
        'api-reference/conventions',
        'api-reference/endpoints',
        'api-reference/drawing-the-warehouse',
        'api-reference/bulk-import',
        {
          type: 'category',
          label: 'REST API (from openapi.yaml)',
          collapsed: true,
          items: restApiSidebar,
        },
      ],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      collapsed: false,
      items: [
        'ecosystem/context-map',
        'ecosystem/consuming-this-service',
      ],
    },
    {
      type: 'category',
      label: 'AI Ecosystem (MCP)',
      collapsed: false,
      items: ['mcp/governance-charter'],
    },
    {
      type: 'category',
      label: 'Analytics (Data Product)',
      collapsed: false,
      items: ['analytics/catalog-growth-report'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      collapsed: false,
      link: {type: 'doc', id: 'adr/index'},
      items: [
        'adr/0001-hexagonal-ports-and-adapters',
        'adr/0002-hierarchical-location-code',
        'adr/0003-placement-rules-at-registration-time',
        'adr/0004-rfc-7807-from-day-one',
        'adr/0005-one-way-decommission',
        'adr/0006-partial-success-bulk-import',
        'adr/0007-mcp-inbound-adapter',
        'adr/0008-location-classification-read-endpoint',
        'adr/0009-kafka-integration-publisher',
        'adr/0010-analytical-data-product',
      ],
    },
  ],
};

export default sidebars;
